// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfiniruuwuacscdxsola.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmaW5pcnV1d3VhY3NjZHhzb2xhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTQ5NzAsImV4cCI6MjA2NTU5MDk3MH0.7GYLad4-sow0RPj9uMtFr8DxjbpGF-dXi5n74e-NLm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);