// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vscrutrrbmvchkcpello.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzY3J1dHJyYm12Y2hrY3BlbGxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDM2OTUsImV4cCI6MjA2MjM3OTY5NX0.oeHNVkSiN8h8UcwofviPuZqWJ-PI1Jqo0VcTE3FQ-hY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);